name: Auto Merge Dev to Main

on:
  push:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Attempt to merge dev into main
        id: merge
        run: |
          git fetch
          git checkout main
          git merge dev --allow-unrelated-histories

      - name: Check for merge conflicts and resolve
        if: failure()
        run: |
          echo "Merge conflict detected. Resolving conflicts..."
          git add .
          git commit -m "Automatically resolved merge conflict by using dev branch changes"
          git push origin main

      - name: Push if no conflicts
        if: success()
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
